name: Automerge

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3